apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafbat-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: mkcert
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kafbat.dev.local
      secretName: kafbat-tls
  rules:
    - host: kafbat.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafbat-ui-kafka-ui
                port:
                  number: 80
